import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const handelVisible = () => {
    if (visble == "hidden") {
      setVisible("block");
    } else {
      setVisible("hidden");
    }
  };

  const [visble, setVisible] = useState("hidden");
  return (
    <div className="{styles.container}">
      <Head>
        <title>Movie Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="nav bg-black text-white text-center">
        <div className="navbar flex justify-between items-center p-2 md:hidden">
          <div clasName="flex justify-center items-center">
            <div
              className="hamburger inline-block p-1 cursor-pointer"
              onClick={handelVisible}
            >
              <div className="line h-0.5 w-6 my-1 bg-white"></div>
              <div className="line h-0.5 w-6 my-1 bg-white"></div>
              <div className="line h-0.5 w-6 my-1 bg-white"></div>
            </div>
          </div>
          <div className="text-xl md:hidden">Movie Blog</div>
          {/* <div className="Cart text-center md:hidden">Cart Account</div> */}
          <div className="mode md:hidden">Dark Mode</div>
        </div>

        <ul className={`justify-between px-20 md:flex ${visble}`}>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            MOVIE BLOG
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            SR EXCLUSIVES
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            MOVIE NEWS
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            TV NEWS
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            REVIEWS
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            INTERVIEWS
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            TECH
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            MORE
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            FOLLOW US
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            DARK MODE
          </li>
          <li className="cursor-pointer text-xs font-bold hover:bg-sky-700 px-1 py-3">
            SEARCH
          </li>
        </ul>
      </nav>

        <div className="h-100 pt-8 text-center font-bold text-2xl  md:text-4xl" >
          THE #1 MOVIE & TV NEWS WEBSITE
        </div>
      <main className="px-3 sm:px-6 md:px-9">

        <div className="blogContainer md:grid md:grid-cols-3 md:gap-4">
          <div className="md:col-span-2">
            <h2 className="text-xl text-yellow-600 py-4 font-bold underline md:text-2xl">
              Latest
            </h2>
            <div className="singleBlog shadow hover:shadow-md sm:rounded md:rounded-md">
              <div className="card sm:grid sm:grid-cols-2 sm:gap-3 sm:content-center">
                <div className="imgCard">
                  <img
                    className="w-full h-64"
                    src="https://source.unsplash.com/collection/1346951/500x500?sig=1"
                  />
                </div>
                <div className="textCard content-center grid">
                  <p className="text-yellow-600">Type</p>
                  <a className="text-2xl font-bold hover:underline">Title</a>
                  <p className="text-slate-600">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Aspernatur officiis ad consequuntur a hic molestiae
                    voluptatem
                  </p>
                  <p className="text-slate-500">
                    Author <span className="text-slate-400">Date</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="trendingBlog">
            <h2 className="text-xl py-4 text-yellow-600 font-bold underline md:text-2xl">
              Trending
            </h2>
            <div className="tredingItem sm:flex sm:justify-between sm:items-center md:block">
              <div className="singleBlog py-4">
                <div className="imgCard">
                  <img
                    className="w-full sm:64 md:w-full h-64"
                    src="https://source.unsplash.com/collection/1346951/500x500?sig=1"
                  />
                  <p className="text-yellow-600">Type</p>
                  <a className="text-2xl font-bold hover:underline">Title</a>
                  <hr />
                </div>
              </div>
              <div className="singleBlog">
                <div className="imgCard">
                  <img
                    className="w-full sm:w-64 md:w-full h-64"
                    src="https://source.unsplash.com/collection/1346951/500x500?sig=1"
                  />
                  <p className="text-yellow-600">Type</p>
                  <a className="text-2xl font-bold hover:underline">Title</a>
                  <hr />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-black text-white h-32 w-full text-center">
        <h1 className="p-4">Powered by Moive Blog ©2022</h1>
        <div className="names">
          <div className="name">
            <p className="text-yellow-600">Created by: Muhammad Nur</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
