import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Nav";
import Link from "next/link";
import Blog from "../components/Blog";
import Footer from "../components/Footer";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="{styles.container}">
      <Head>
        <title>Flick Thesis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <main className="px-3 sm:px-6 md:px-9">
        <Blog />
      </main>
      <Footer />
    </div>
  );
}
