import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Blogs from "../components/Blogs";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="{styles.container}">
      <Head>
        <title>Flick Thesis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />

      <Blogs />
    </div>
  );
}
